
package org.my.homeworks.generated_sources;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://homeworks.my.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.my.homeworks.generated_sources.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderById", targetNamespace = "http://homeworks.my.org/", className = "org.my.homeworks.generated_sources.GetOrderById")
    @ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://homeworks.my.org/", className = "org.my.homeworks.generated_sources.GetOrderByIdResponse")
    @Action(input = "http://homeworks.my.org/OrderService/getOrderByIdRequest", output = "http://homeworks.my.org/OrderService/getOrderByIdResponse")
    public Order getOrderById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://homeworks.my.org/", className = "org.my.homeworks.generated_sources.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://homeworks.my.org/", className = "org.my.homeworks.generated_sources.AddOrderResponse")
    @Action(input = "http://homeworks.my.org/OrderService/addOrderRequest", output = "http://homeworks.my.org/OrderService/addOrderResponse")
    public void addOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://homeworks.my.org/", className = "org.my.homeworks.generated_sources.GetAllOrders")
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://homeworks.my.org/", className = "org.my.homeworks.generated_sources.GetAllOrdersResponse")
    @Action(input = "http://homeworks.my.org/OrderService/getAllOrdersRequest", output = "http://homeworks.my.org/OrderService/getAllOrdersResponse")
    public List<Object> getAllOrders();

}
